[2020-10-30 20:19:16] php.DEBUG: Warning: filemtime(): stat failed for D:\Symfony\progetto_symfony\config\routes\dev\twig.yaml {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"D:\\\\Xampp\\\\htdocs\\\\progetto_symfony\\\\vendor\\\\symfony\\\\config\\\\Resource\\\\FileResource.php\",\"line\":63,\"trace\":[{\"file\":\"D:\\\\Xampp\\\\htdocs\\\\progetto_symfony\\\\vendor\\\\symfony\\\\config\\\\Resource\\\\SelfCheckingResourceChecker.php\",\"line\":34,\"function\":\"isFresh\",\"class\":\"Symfony\\\\Component\\\\Config\\\\Resource\\\\FileResource\",\"type\":\"->\"}],\"count\":1})"} []
[2020-10-30 20:19:52] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-30 20:19:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-30 20:19:53] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/" is not callable: Class "App\Controller\InvoiceController" does not exist." at D:\Xampp\htdocs\progetto_symfony\vendor\symfony\http-kernel\Controller\ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/\" is not callable: Class \"App\\Controller\\InvoiceController\" does not exist. at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\http-kernel\\Controller\\ControllerResolver.php:91, InvalidArgumentException(code: 0): Class \"App\\Controller\\InvoiceController\" does not exist. at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\http-kernel\\Controller\\ControllerResolver.php:179)"} []
[2020-10-30 20:21:38] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-30 20:21:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-30 20:21:38] php.DEBUG: Warning: filemtime(): stat failed for D:\Symfony\progetto_symfony\vendor\symfony\validator\Resources\translations\validators.en.xlf {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"D:\\\\Xampp\\\\htdocs\\\\progetto_symfony\\\\vendor\\\\symfony\\\\config\\\\Resource\\\\FileResource.php\",\"line\":63,\"trace\":[{\"file\":\"D:\\\\Xampp\\\\htdocs\\\\progetto_symfony\\\\vendor\\\\symfony\\\\config\\\\Resource\\\\SelfCheckingResourceChecker.php\",\"line\":34,\"function\":\"isFresh\",\"class\":\"Symfony\\\\Component\\\\Config\\\\Resource\\\\FileResource\",\"type\":\"->\"}],\"count\":1})"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:21:38] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-30 20:24:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:24:32] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-30 20:25:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:25:03] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-30 20:31:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:31:33] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-30 20:31:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-30 20:31:41] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 11:20:17] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:20:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:20:18] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 11:20:19] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 11:20:20] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:20:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 11:20:32] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 11:21:03] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:21:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:21:04] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 97 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:97, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:27)"} []
[2020-10-31 11:26:30] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:26:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:26:30] doctrine.DEBUG: INSERT INTO row_invoice (description) VALUES('ddd'); [] []
[2020-10-31 11:26:31] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:29:18] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:29:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:29:18] doctrine.DEBUG: INSERT INTO row_invoice (description) VALUES('ddd'); [] []
[2020-10-31 11:29:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`Id Invoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:30:16] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:30:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:30:16] doctrine.DEBUG: INSERT INTO row_invoice (Id invoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 11:30:16] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO row_invoice (Id invoice, description) VALUES(1, 'ddd');':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(1, 'ddd')' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (Id invoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:32:28] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:32:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:32:29] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 11:32:29] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:33:00] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:33:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:33:00] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 11:33:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:35:16] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:35:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:35:16] doctrine.DEBUG: INSERT INTO invoice (Number invoice) VALUES(1); [] []
[2020-10-31 11:35:16] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO invoice (Number invoice) VALUES(1);':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO invoice (Number invoice) VALUES(1);':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:36:15] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:36:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:36:15] doctrine.DEBUG: INSERT INTO invoice (Number invoice) VALUES('1'); [] []
[2020-10-31 11:36:15] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO invoice (Number invoice) VALUES('1');':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES('1')' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO invoice (Number invoice) VALUES('1');':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES('1')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES('1')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES('1')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:36:48] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:36:48] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:36:48] doctrine.DEBUG: INSERT INTO invoice (Numberinvoice) VALUES('1'); [] []
[2020-10-31 11:36:48] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at D:\Xampp\htdocs\progetto_symfony\vendor\symfony\http-kernel\HttpKernel.php line 169 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\http-kernel\\HttpKernel.php:169)"} []
[2020-10-31 11:37:35] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:37:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:37:35] doctrine.DEBUG: INSERT INTO invoice (Numberinvoice) VALUES('1'); [] []
[2020-10-31 11:37:35] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at D:\Xampp\htdocs\progetto_symfony\vendor\symfony\http-kernel\HttpKernel.php line 169 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\http-kernel\\HttpKernel.php:169)"} []
[2020-10-31 11:38:36] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:38:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:38:36] doctrine.DEBUG: INSERT INTO invoice (Numberinvoice) VALUES('1'); [] []
[2020-10-31 11:38:36] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Driver\PDOException: "SQLSTATE[HY000]: General error" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php line 180 {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:180, PDOException(code: HY000): SQLSTATE[HY000]: General error at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:175)"} []
[2020-10-31 11:39:06] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:39:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:39:06] doctrine.DEBUG: INSERT INTO invoice (Numberinvoice) VALUES('1'); [] []
[2020-10-31 11:39:06] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (ok given)." at D:\Xampp\htdocs\progetto_symfony\vendor\symfony\http-kernel\HttpKernel.php line 169 {"exception":"[object] (LogicException(code: 0): The controller must return a response (ok given). at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\http-kernel\\HttpKernel.php:169)"} []
[2020-10-31 11:39:51] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:39:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:39:51] doctrine.DEBUG: INSERT INTO invoice (Numberinvoice) VALUES('1'); [] []
[2020-10-31 11:40:51] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:40:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:40:51] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 11:40:58] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:40:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:40:58] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 11:41:21] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:41:21] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:41:21] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 11:42:25] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:42:25] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:42:25] doctrine.DEBUG: INSERT INTO row_invoice (Id invoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:42:25] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO row_invoice (Id invoice, description) VALUES(10, 'sss');':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (Id invoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:43:13] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:43:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:43:13] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:43:13] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:44:20] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:44:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:44:20] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:44:20] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:44:43] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:44:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:44:43] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:51:07] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:51:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:51:07] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:51:07] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'IdInvoice' in 'field list'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 64 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'IdInvoice' in 'field list' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:64, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'IdInvoice' in 'field list' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'IdInvoice' in 'field list' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:51:18] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:51:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:51:18] doctrine.DEBUG: INSERT INTO row_invoice (Id invoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:51:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO row_invoice (Id invoice, description) VALUES(10, 'sss');':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (Id invoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice, description) VALUES(10, 'sss')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:51:45] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:51:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:51:45] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:51:45] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:52:04] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:52:04] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:52:04] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:52:04] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:53:31] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:53:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:53:31] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:53:31] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:54:03] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:54:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:54:03] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:54:03] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `row_invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `row_invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `row_invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `row_invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:56:30] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:56:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:56:30] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss'); [] []
[2020-10-31 11:56:30] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(10, 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:57:35] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:57:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:57:35] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES('10', 'sss'); [] []
[2020-10-31 11:57:35] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES('10', 'sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES('10', 'sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:57:56] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:57:56] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:57:56] doctrine.DEBUG: INSERT INTO row_invoice (description) VALUES('sss'); [] []
[2020-10-31 11:57:56] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 11:59:40] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 11:59:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 11:59:40] doctrine.DEBUG: INSERT INTO row_invoice (description) VALUES('sss'); [] []
[2020-10-31 11:59:40] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('sss');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (description) VALUES('sss');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:00:36] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:00:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:00:36] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:00:36] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:05:02] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:05:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:05:02] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:05:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:05:22] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:05:22] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:05:22] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:05:22] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Idinvoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:06:41] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:06:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:06:41] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:06:41] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:07:34] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:07:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:07:34] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:07:34] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:08:07] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:08:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:08:07] doctrine.DEBUG: INSERT INTO row_invoice (Id Invoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:08:07] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO row_invoice (Id Invoice, description) VALUES(1, 'ddd');':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (Id Invoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:10:20] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:10:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:10:20] doctrine.DEBUG: INSERT INTO invoice (Number invoice) VALUES(1); [] []
[2020-10-31 12:10:20] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO invoice (Number invoice) VALUES(1);':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO invoice (Number invoice) VALUES(1);':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'invoice) VALUES(1)' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:10:54] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:10:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:10:54] doctrine.DEBUG: INSERT INTO invoice (NumberInvoice) VALUES(1); [] []
[2020-10-31 12:11:08] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:11:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:11:08] doctrine.DEBUG: INSERT INTO row_invoice (Id Invoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:11:08] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO row_invoice (Id Invoice, description) VALUES(1, 'ddd');':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 83 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (Id Invoice, description) VALUES(1, 'ddd');':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:83, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Invoice, description) VALUES(1, 'ddd')' at line 1 at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 12:11:30] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:11:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:11:30] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:14:23] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::insertAction","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:14:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:14:23] doctrine.DEBUG: INSERT INTO invoice (NumberInvoice) VALUES(1); [] []
[2020-10-31 12:14:23] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'ddd'); [] []
[2020-10-31 12:17:47] php.INFO: User Deprecated: Duplicate key "index" detected whilst parsing YAML. Silent handling of duplicate mapping keys in YAML is deprecated since Symfony 3.2 and will throw \Symfony\Component\Yaml\Exception\ParseException in 4.0 in D:\Xampp\htdocs\progetto_symfony\config/routes.yaml in "D:\Xampp\htdocs\progetto_symfony\config/routes.yaml" on line 8. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Duplicate key \"index\" detected whilst parsing YAML. Silent handling of duplicate mapping keys in YAML is deprecated since Symfony 3.2 and will throw \\Symfony\\Component\\Yaml\\Exception\\ParseException in 4.0 in D:\\Xampp\\htdocs\\progetto_symfony\\config/routes.yaml in \"D:\\Xampp\\htdocs\\progetto_symfony\\config/routes.yaml\" on line 8. at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\yaml\\Parser.php:396)"} []
[2020-10-31 12:17:47] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 12:17:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 12:17:47] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 17:52:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:52:39] php.INFO: User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since Symfony 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since Symfony 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead. at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\form\\Form.php:739)"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:52:39] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 17:53:02] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 17:53:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:53:02] php.CRITICAL: Call to undefined method Symfony\Component\Form\Form::isSubmit() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Symfony\\Component\\Form\\Form::isSubmit() at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:18)"} []
[2020-10-31 17:53:02] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "isSubmit" of class "Symfony\Component\Form\Form". Did you mean to call e.g. "isSubmitted" or "submit"?" at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 18 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"isSubmit\" of class \"Symfony\\Component\\Form\\Form\".\nDid you mean to call e.g. \"isSubmitted\" or \"submit\"? at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:18)"} []
[2020-10-31 17:53:15] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 17:53:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:53:16] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 17:53:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:53:46] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 17:55:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:55:40] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 17:55:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:55:57] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 17:58:33] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 17:58:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:58:33] doctrine.DEBUG: INSERT INTO invoice (NumberInvoice) VALUES(1); [] []
[2020-10-31 17:58:33] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'frfrf'); [] []
[2020-10-31 17:58:33] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'frfrf');':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 59 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'frfrf');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:59, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 17:59:27] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 17:59:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:59:28] php.INFO: User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since Symfony 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since Symfony 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead. at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\form\\Form.php:739)"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:59:28] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 17:59:39] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 17:59:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 17:59:40] php.INFO: User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since Symfony 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Call Form::isValid() with an unsubmitted form is deprecated since Symfony 3.2 and will throw an exception in 4.0. Use Form::isSubmitted() before Form::isValid() instead. at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\form\\Form.php:739)"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 17:59:40] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 18:02:59] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:02:59] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:02:59] php.CRITICAL: Call to undefined method Symfony\Component\Form\Form::getDescription() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Symfony\\Component\\Form\\Form::getDescription() at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:19)"} []
[2020-10-31 18:02:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getDescription" of class "Symfony\Component\Form\Form"." at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 19 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getDescription\" of class \"Symfony\\Component\\Form\\Form\". at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:19)"} []
[2020-10-31 18:04:03] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:04:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:04:05] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 18:04:26] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:04:26] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:04:26] doctrine.DEBUG: INSERT INTO invoice (NumberInvoice) VALUES(1); [] []
[2020-10-31 18:04:26] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'frfrf'); [] []
[2020-10-31 18:04:26] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'frfrf');':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 59 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(1, 'frfrf');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:59, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 18:04:47] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:04:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:04:47] doctrine.DEBUG: INSERT INTO invoice (NumberInvoice) VALUES(2); [] []
[2020-10-31 18:04:47] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(2, 'frfrf'); [] []
[2020-10-31 18:04:56] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 18:04:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:04:57] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 18:05:11] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:05:11] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:05:11] doctrine.DEBUG: INSERT INTO invoice (NumberInvoice) VALUES(2); [] []
[2020-10-31 18:05:11] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(2, 'frfrf'); [] []
[2020-10-31 18:05:11] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(2, 'frfrf');':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'Id Invoice'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 59 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description) VALUES(2, 'frfrf');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:59, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 18:06:00] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:06:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:06:01] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:06:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Number","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Date","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:06:23] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 18:06:34] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:06:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:06:34] doctrine.DEBUG: INSERT INTO invoice (NumberInvoice) VALUES(3); [] []
[2020-10-31 18:06:34] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description) VALUES(3, 'ttryvbb'); [] []
[2020-10-31 18:09:21] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:09:21] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:09:21] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "dateInvoice" nor one of the methods "getDateInvoice()", "dateInvoice()", "isDateInvoice()", "hasDateInvoice()", "__get()" exist and have public access in class "App\Entity\Invoice"." at D:\Xampp\htdocs\progetto_symfony\vendor\symfony\property-access\PropertyAccessor.php line 516 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"dateInvoice\" nor one of the methods \"getDateInvoice()\", \"dateInvoice()\", \"isDateInvoice()\", \"hasDateInvoice()\", \"__get()\" exist and have public access in class \"App\\Entity\\Invoice\". at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\property-access\\PropertyAccessor.php:516)"} []
[2020-10-31 18:11:56] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 18:11:56] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:11:56] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "number" nor one of the methods "number()", "getnumber()"/"isnumber()"/"hasnumber()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView"." at D:\Xampp\htdocs\progetto_symfony\templates\invoice.html.twig line 10 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Neither the property \"number\" nor one of the methods \"number()\", \"getnumber()\"/\"isnumber()\"/\"hasnumber()\" or \"__call()\" exist and have public access in class \"Symfony\\Component\\Form\\FormView\". at D:\\Xampp\\htdocs\\progetto_symfony\\templates\\invoice.html.twig:10)"} []
[2020-10-31 18:12:01] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 18:12:01] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:12:01] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "number" nor one of the methods "number()", "getnumber()"/"isnumber()"/"hasnumber()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView"." at D:\Xampp\htdocs\progetto_symfony\templates\invoice.html.twig line 10 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Neither the property \"number\" nor one of the methods \"number()\", \"getnumber()\"/\"isnumber()\"/\"hasnumber()\" or \"__call()\" exist and have public access in class \"Symfony\\Component\\Form\\FormView\". at D:\\Xampp\\htdocs\\progetto_symfony\\templates\\invoice.html.twig:10)"} []
[2020-10-31 18:12:39] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 18:12:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:12:40] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "number" nor one of the methods "number()", "getnumber()"/"isnumber()"/"hasnumber()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView"." at D:\Xampp\htdocs\progetto_symfony\templates\invoice.html.twig line 10 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Neither the property \"number\" nor one of the methods \"number()\", \"getnumber()\"/\"isnumber()\"/\"hasnumber()\" or \"__call()\" exist and have public access in class \"Symfony\\Component\\Form\\FormView\". at D:\\Xampp\\htdocs\\progetto_symfony\\templates\\invoice.html.twig:10)"} []
[2020-10-31 18:13:02] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 18:13:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:13:03] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 18:21:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 18:21:08] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 18:22:12] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:22:12] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:22:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Object of class DateTime could not be converted to string" at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 32 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:32)"} []
[2020-10-31 18:23:44] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:23:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:23:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Object of class DateTime could not be converted to string" at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 32 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:32)"} []
[2020-10-31 18:23:50] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:23:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:23:51] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Object of class DateTime could not be converted to string" at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 32 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:32)"} []
[2020-10-31 18:25:19] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:25:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:25:20] php.CRITICAL: Call to undefined function App\Controller\format() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function App\\Controller\\format() at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:26)"} []
[2020-10-31 18:25:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "format" from namespace "App\Controller"." at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 26 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"format\" from namespace \"App\\Controller\". at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:26)"} []
[2020-10-31 18:25:35] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:25:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:25:35] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2019-05-05', 45, 1); [] []
[2020-10-31 18:25:35] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54'); [] []
[2020-10-31 18:25:35] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 18:25:58] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:25:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:25:58] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2019-05-05', 45, 1); [] []
[2020-10-31 18:25:58] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54'); [] []
[2020-10-31 18:25:58] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 18:26:18] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 18:26:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 18:26:18] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2019-05-05', 45, 1); [] []
[2020-10-31 18:26:18] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54'); [] []
[2020-10-31 18:26:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 19:38:09] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 19:38:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:38:09] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2019-05-05', 45, 1); [] []
[2020-10-31 19:38:09] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54'); [] []
[2020-10-31 19:38:09] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(3, 'reerer', 7, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-10-31 19:39:08] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 19:39:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:39:09] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2019-05-05', 45, 1); [] []
[2020-10-31 19:39:09] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'reerer', 7, '45.4', '6.8', '9.54'); [] []
[2020-10-31 19:39:12] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 19:39:12] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 19:39:12] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 19:42:24] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 19:42:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:42:24] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2020-12-12', 789687897, 1); [] []
[2020-10-31 19:42:24] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'rgryhtrgtrgrtg', 70, '22.4', '6.43', '10.34'); [] []
[2020-10-31 19:42:45] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 19:42:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 19:42:45] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 19:45:47] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 19:45:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:45:47] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2020-03-12', 789687897, 1); [] []
[2020-10-31 19:45:48] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'rgryhtrgtrgrtg', 70, '22.4', '6.43', '10.34'); [] []
[2020-10-31 19:52:20] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-10-31 19:52:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-10-31 19:52:20] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-10-31 19:52:23] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-10-31 19:52:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-31 19:52:24] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2020-03-12', 789687897, 1); [] []
[2020-10-31 19:52:24] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'rgryhtrgtrgrtg', 70, '22.4', '6.43', '10.34'); [] []
[2020-11-01 12:20:41] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-11-01 12:20:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:20:42] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-11-01 12:21:02] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:21:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:21:03] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 3, 1); [] []
[2020-11-01 12:21:03] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:21:15] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-11-01 12:21:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:21:15] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-11-01 12:21:20] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:21:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:21:20] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 1); [] []
[2020-11-01 12:21:20] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:21:20] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 59 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:59, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:21:51] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:21:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:21:51] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 1); [] []
[2020-11-01 12:21:51] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:21:51] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 59 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:59, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:22:13] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:22:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:22:13] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 1); [] []
[2020-11-01 12:22:13] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:22:13] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:22:33] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:22:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:22:33] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 1); [] []
[2020-11-01 12:22:33] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:22:33] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:23:07] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:23:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:23:07] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 1); [] []
[2020-11-01 12:23:07] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:23:10] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-11-01 12:23:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:23:10] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-11-01 12:23:13] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:23:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:23:13] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 1); [] []
[2020-11-01 12:23:13] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:23:13] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 59 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:59, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:25:03] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:25:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:25:03] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: i" at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined variable: i at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:34)"} []
[2020-11-01 12:26:00] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:26:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:26:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: i" at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined variable: i at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:34)"} []
[2020-11-01 12:28:30] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:28:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:28:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: i" at D:\Xampp\htdocs\progetto_symfony\src\Controller\InvoiceController.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined variable: i at D:\\Xampp\\htdocs\\progetto_symfony\\src\\Controller\\InvoiceController.php:34)"} []
[2020-11-01 12:28:51] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:28:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:28:51] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 1); [] []
[2020-11-01 12:28:52] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:28:52] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice'" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 59 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(1, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:59, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'Id Invoice' at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:29:10] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:29:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:29:10] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 11); [] []
[2020-11-01 12:29:10] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(11, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:29:11] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(11, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(11, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:30:11] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:30:11] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:30:11] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 11); [] []
[2020-11-01 12:30:11] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(11, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:30:11] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(11, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(11, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:30:58] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:30:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:30:58] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2015-01-01', 34, 11); [] []
[2020-11-01 12:30:58] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(11, 'ww', 4, '45.4', '6.8', '9.54'); [] []
[2020-11-01 12:30:58] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(11, 'ww', 4, '45.4', '6.8', '9.54');':  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`))" at D:\Xampp\htdocs\progetto_symfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)\r\n                 VALUES(11, 'ww', 4, '45.4', '6.8', '9.54');':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:131, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`progetto_symfony`.`row_invoice`, CONSTRAINT `Id invoice` FOREIGN KEY (`IdInvoice`) REFERENCES `invoice` (`Id`)) at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:129)"} []
[2020-11-01 12:32:25] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-11-01 12:32:25] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:32:25] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "Could not load type "Symfony\Component\Form\Extension\Core\Type\FloatType": class does not exist." at D:\Xampp\htdocs\progetto_symfony\vendor\symfony\form\FormRegistry.php line 86 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"Symfony\\Component\\Form\\Extension\\Core\\Type\\FloatType\": class does not exist. at D:\\Xampp\\htdocs\\progetto_symfony\\vendor\\symfony\\form\\FormRegistry.php:86)"} []
[2020-11-01 12:34:51] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"GET"} []
[2020-11-01 12:34:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Number invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Date invoice","domain":"messages","locale":"en"} []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Description","domain":"messages","locale":"en"} []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Quantity","domain":"messages","locale":"en"} []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Amount","domain":"messages","locale":"en"} []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Amount i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Total i v a","domain":"messages","locale":"en"} []
[2020-11-01 12:34:51] translation.WARNING: Translation not found. {"id":"Submit","domain":"messages","locale":"en"} []
[2020-11-01 12:35:33] request.INFO: Matched route "index". {"route":"index","route_parameters":{"_controller":"App\\Controller\\InvoiceController::index","_route":"index"},"request_uri":"http://localhost/progetto_symfony/public/","method":"POST"} []
[2020-11-01 12:35:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-11-01 12:35:33] doctrine.DEBUG: INSERT INTO invoice (DateInvoice, NumberInvoice, IdClient) VALUES('2018-07-06', 56, 1); [] []
[2020-11-01 12:35:34] doctrine.DEBUG: INSERT INTO row_invoice (IdInvoice, description, quantity, amount, amountIVA, totalIVA)                  VALUES(1, 'ee5t', 5, '5', '6.8', '10.34'); [] []
